In [3]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.rcParams["figure.figsize"] = (10, 4)

In [4]:
df = pd.read_csv("./nyc-pin-oaks-2015.csv")

In [5]:
df

,Unnamed: 0,tree_id,tree_dbh,health,steward,postcode,borough,cncldist,nta_name,nta,latitude,longitude
0,1,200540,21,Fair,NaN,11357,Queens,19,Whitestone,QN49,40.794111,-73.818679
1,56,197978,7,Good,1or2,11365,Queens,20,Queensboro Hill,QN62,40.740687,-73.808260
2,58,178601,10,Fair,NaN,10312,Staten Island,51,Annadale-Huguenot-Prince's Bay-Eltingville,SI01,40.532113,-74.156181
3,59,184317,5,Good,NaN,10458,Bronx,15,Belmont,BX06,40.856774,-73.890979
4,60,200225,8,Good,1or2,10024,Manhattan,6,Upper West Side,MN12,40.789936,-73.977212
...,...,...,...,...,...,...,...,...,...,...,...,...
53180,683775,192812,5,Good,NaN,10014,Manhattan,3,West Village,MN23,40.739913,-74.004892
53181,683776,179969,11,Good,NaN,11210,Brooklyn,45,Flatbush,BK42,40.635175,-73.953391
53182,683781,155348,20,Good,NaN,11226,Brooklyn,40,Flatbush,BK42,40.645694,-73.958179
53183,683782,184210,3,Good,1or2,10457,Bronx,15,Mount Hope,BX41,40.854570,-73.899192
53184,683783,155433,25,Good,NaN,11211,Brooklyn,34,North Side-South Side,BK73,40.713211,-73.954944

In [6]:
%pip install folium

Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: folium in c:\users\marya\appdata\local\programs\python\python312\lib\site-packages (0.20.0)
Requirement already satisfied: branca>=0.6.0 in c:\users\marya\appdata\local\programs\python\python312\lib\site-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in c:\users\marya\appdata\local\programs\python\python312\lib\site-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in c:\users\marya\appdata\local\programs\python\python312\lib\site-packages (from folium) (2.4.2)
Requirement already satisfied: requests in c:\users\marya\appdata\local\programs\python\python312\lib\site-packages (from folium) (2.33.1)
Requirement already satisfied: xyzservices in c:\users\marya\appdata\local\programs\python\python312\lib\site-packages (from folium) (2026.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\marya\appdata\local\programs\python\python312\lib\site-packages (from jinja2>=2.9->folium) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\marya\appdata\local\programs\python\python312\lib\site-packages (from requests->folium) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\marya\appdata\local\programs\python\python312\lib\site-packages (from requests->folium) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\marya\appdata\local\programs\python\python312\lib\site-packages (from requests->folium) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\marya\appdata\local\programs\python\python312\lib\site-packages (from requests->folium) (2026.2.25)

[notice] A new release of pip is available: 24.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import folium

In [9]:
fig = folium.Figure(width=800, height=320) #to set the size of the map on your own
folium.Map (
    location=(40.693, -73.9875),
    zoom_start=15,
    tiles="USGS.USTopo"
)
fig.add_child

###add markers

In [10]:
fig = folium.Figure(width=800, height=320) #to set the size of the map on your own
m = folium.Map (
    location=(40.693, -73.9875), zoom_start=16)
folium.Marker (location=(40.693, -73.9875),
               tooltip = "hello!",
               popup="where the magic happens!",
               icon=folium.Icon(icon="star", color="blue")
               ).add_to(m) #add a marker for each point that you want to mark
fig.add_child(m)

In [31]:
fig = folium.Figure(width=800, height=320) #to set the size of the map on your own
m = folium.Map (location=(40.693, -73.9875), zoom_start=16)

#iterate over our dataset
#for each row, add a market at the location of that tree

for idx, item in df.sample(1000).iterrows(): 
    print(item)

    folium.Marker (location=(item['latitude'], item['longitude']),
              tooltip = str(item['tree_id']),
               popup=item['health'],
               icon=folium.Icon(icon="star", color="green")
               ).add_to(m) #add a marker for each point that you want to mark
fig.add_child(m)

Unnamed: 0             619187
tree_id                111327
tree_dbh                   28
health                   Good
steward                   NaN
postcode                   83
borough             Manhattan
cncldist                    6
nta_name      Upper West Side
nta                      MN12
latitude            40.786976
longitude          -73.967964
Name: 48244, dtype: object
Unnamed: 0                   120532
tree_id                      325423
tree_dbh                          6
health                         Good
steward                         NaN
postcode                      10462
borough                       Bronx
cncldist                         13
nta_name      Westchester-Unionport
nta                            BX59
latitude                  40.834422
longitude                -73.840631
Name: 9060, dtype: object
Unnamed: 0                                              46641
tree_id                                                246995
tree_dbh                                                    4
health                                                   Fair
steward                                                   NaN
postcode                                                10473
borough                                                 Bronx
cncldist                                                   18
nta_name      Soundview-Castle Hill-Clason Point-Harding Park
nta                                                      BX09
latitude                                            40.807305
longitude                                          -73.855783
Name: 3656, dtype: object
Unnamed: 0       367090
tree_id          587446
tree_dbh             23
health             Good
steward             NaN
postcode          11422
borough          Queens
cncldist             31
nta_name       Rosedale
nta                QN05
latitude      40.661621
longitude    -73.730293
Name: 26621, dtype: object
Unnamed: 0                   192814
tree_id                      400748
tree_dbh                         25
health                         Good
steward                         NaN
postcode                      10306
borough               Staten Island
cncldist                         50
nta_name      Oakwood-Oakwood Beach
nta                            SI25
latitude                  40.562016
longitude                -74.109804
Name: 14184, dtype: object
Unnamed: 0                                        313203
tree_id                                           522084
tree_dbh                                               9
health                                              Good
steward                                              NaN
postcode                                           10019
borough                                        Manhattan
cncldist                                               3
nta_name      Hudson Yards-Chelsea-Flatiron-Union Square
nta                                                 MN13
latitude                                       40.761565
longitude                                     -74.001656
Name: 22537, dtype: object
Unnamed: 0                                               662088
tree_id                                                  169904
tree_dbh                                                      4
health                                                     Poor
steward                                                     NaN
postcode                                                  11694
borough                                                  Queens
cncldist                                                     32
nta_name      Breezy Point-Belle Harbor-Rockaway Park-Broad ...
nta                                                        QN10
latitude                                              40.569919
longitude                                            -73.862727
Name: 51329, dtype: object
Unnamed: 0           216414
tree_id              405574
tree_dbh                 20
health                 Good
steward                 NaN
postcode              10312
borough       Staten Island
cncldist                 51
nta_name      Arden Heights
nta                    SI48
latitude          40.541924
longitude         -74.19609
Name: 15764, dtype: object
Unnamed: 0                                       354603
tree_id                                          552352
tree_dbh                                             14
health                                             Good
steward                                             NaN
postcode                                          10301
borough                                   Staten Island
cncldist                                             49
nta_name      West New Brighton-New Brighton-St. George
nta                                                SI22
latitude                                      40.639057
longitude                                    -74.096634
Name: 25200, dtype: object
Unnamed: 0                                             298465
tree_id                                                504459
tree_dbh                                                    2
health                                                   Fair
steward                                                  1or2
postcode                                                10473
borough                                                 Bronx
cncldist                                                   18
nta_name      Soundview-Castle Hill-Clason Point-Harding Park
nta                                                      BX09
latitude                                            40.821108
longitude                                          -73.848148
Name: 21398, dtype: object
Unnamed: 0                                            336558
tree_id                                               554296
tree_dbh                                                   2
health                                                  Good
steward                                                 1or2
postcode                                               11234
borough                                             Brooklyn
cncldist                                                  46
nta_name      Georgetown-Marine Park-Bergen Beach-Mill Basin
nta                                                     BK45
latitude                                           40.611879
longitude                                         -73.936586
Name: 23971, dtype: object
Unnamed: 0        357033
tree_id           562020
tree_dbh              22
health              Good
steward              NaN
postcode           11357
borough           Queens
cncldist              19
nta_name      Whitestone
nta                 QN49
latitude       40.791704
longitude     -73.808786
Name: 25509, dtype: object
Unnamed: 0                        277814
tree_id                           498748
tree_dbh                              19
health                              Good
steward                              NaN
postcode                           10471
borough                            Bronx
cncldist                              11
nta_name      Spuyten Duyvil-Kingsbridge
nta                                 BX29
latitude                       40.887831
longitude                     -73.898906
Name: 19815, dtype: object
Unnamed: 0        52066
tree_id          252203
tree_dbh              2
health             Good
steward            1or2
postcode          11422
borough          Queens
cncldist             31
nta_name      Laurelton
nta                QN66
latitude      40.682488
longitude    -73.731176
Name: 4030, dtype: object
Unnamed: 0       124915
tree_id          314206
tree_dbh             18
health             Good
steward            1or2
postcode          10467
borough           Bronx
cncldist             15
nta_name      Bronxdale
nta                BX07
latitude      40.858907
longitude    -73.869087
Name: 9495, dtype: object
Unnamed: 0                               586183
tree_id                                   84893
tree_dbh                                     20
health                                     Good
steward                                     NaN
postcode                                  10314
borough                           Staten Island
cncldist                                     50
nta_name      New Springville-Bloomfield-Travis
nta                                        SI05
latitude                              40.603819
longitude                            -74.139658
Name: 45291, dtype: object
Unnamed: 0                                  437996
tree_id                                     632451
tree_dbh                                        27
health                                        Good
steward                                        NaN
postcode                                     11362
borough                                     Queens
cncldist                                        23
nta_name      Douglas Manor-Douglaston-Little Neck
nta                                           QN45
latitude                                 40.756258
longitude                               -73.734469
Name: 32691, dtype: object
Unnamed: 0        154901
tree_id           368735
tree_dbh              19
health              Good
steward              NaN
postcode           10452
borough            Bronx
cncldist              16
nta_name      Highbridge
nta                 BX26
latitude       40.841589
longitude     -73.926538
Name: 11313, dtype: object
Unnamed: 0                               252477
tree_id                                  442032
tree_dbh                                     22
health                                     Good
steward                                     NaN
postcode                                  10305
borough                           Staten Island
cncldist                                     50
nta_name      Old Town-Dongan Hills-South Beach
nta                                        SI36
latitude                              40.591886
longitude                            -74.085922
Name: 18000, dtype: object
Unnamed: 0       681897
tree_id          172854
tree_dbh             10
health             Good
steward             NaN
postcode          11226
borough        Brooklyn
cncldist             40
nta_name        Erasmus
nta                BK95
latitude      40.652307
longitude    -73.949644
Name: 52890, dtype: object
Unnamed: 0       664405
tree_id          122170
tree_dbh             18
health             Good
steward             NaN
postcode          11426
borough          Queens
cncldist             23
nta_name      Bellerose
nta                QN43
latitude      40.734504
longitude    -73.734939
Name: 51504, dtype: object
Unnamed: 0          578145
tree_id              71853
tree_dbh                30
health                Fair
steward                NaN
postcode             11434
borough             Queens
cncldist                28
nta_name      Baisley Park
nta                   QN76
latitude         40.681296
longitude       -73.787775
Name: 44351, dtype: object
Unnamed: 0                        354784
tree_id                           557746
tree_dbh                               6
health                              Good
steward                              NaN
postcode                           10463
borough                            Bronx
cncldist                              11
nta_name      Spuyten Duyvil-Kingsbridge
nta                                 BX29
latitude                       40.885663
longitude                      -73.91203
Name: 25285, dtype: object
Unnamed: 0         443145
tree_id            649769
tree_dbh               37
health               Good
steward               NaN
postcode            11354
borough            Queens
cncldist               19
nta_name      Murray Hill
nta                  QN51
latitude        40.776262
longitude      -73.819589
Name: 33172, dtype: object
Unnamed: 0        91522
tree_id          257834
tree_dbh              3
health             Good
steward             NaN
postcode          11209
borough        Brooklyn
cncldist             43
nta_name      Bay Ridge
nta                BK31
latitude      40.625312
longitude    -74.024999
Name: 7019, dtype: object
Unnamed: 0           459644
tree_id              670199
tree_dbh                 25
health                 Good
steward                 NaN
postcode              11358
borough              Queens
cncldist                 20
nta_name      East Flushing
nta                    QN52
latitude          40.753791
longitude         -73.80243
Name: 34363, dtype: object
Unnamed: 0            123272
tree_id               323163
tree_dbh                  18
health                  Good
steward                  NaN
postcode               10452
borough                Bronx
cncldist                  16
nta_name      West Concourse
nta                     BX63
latitude           40.831213
longitude         -73.925688
Name: 9307, dtype: object
Unnamed: 0                                             289546
tree_id                                                504160
tree_dbh                                                    2
health                                                   Good
steward                                                  1or2
postcode                                                10473
borough                                                 Bronx
cncldist                                                   18
nta_name      Soundview-Castle Hill-Clason Point-Harding Park
nta                                                      BX09
latitude                                            40.817797
longitude                                          -73.861107
Name: 20841, dtype: object
Unnamed: 0                   568126
tree_id                       50725
tree_dbh                          4
health                         Good
steward                         NaN
postcode                      11361
borough                      Queens
cncldist                         19
nta_name      Bayside-Bayside Hills
nta                            QN46
latitude                  40.768557
longitude                -73.784683
Name: 43818, dtype: object
Unnamed: 0          215855
tree_id             424329
tree_dbh                25
health                Good
steward                NaN
postcode             11434
borough             Queens
cncldist                28
nta_name      Baisley Park
nta                   QN76
latitude         40.681229
longitude       -73.781345
Name: 15587, dtype: object
Unnamed: 0           96836
tree_id             313748
tree_dbh                13
health                Good
steward                NaN
postcode             11375
borough             Queens
cncldist                29
nta_name      Forest Hills
nta                   QN17
latitude         40.712695
longitude       -73.856678
Name: 7447, dtype: object
Unnamed: 0                                  255618
tree_id                                     470273
tree_dbh                                        11
health                                        Good
steward                                        NaN
postcode                                     11363
borough                                     Queens
cncldist                                        19
nta_name      Douglas Manor-Douglaston-Little Neck
nta                                           QN45
latitude                                 40.773872
longitude                               -73.749364
Name: 18167, dtype: object
Unnamed: 0           216144
tree_id              400322
tree_dbh                 27
health                 Good
steward                 NaN
postcode              11354
borough              Queens
cncldist                 19
nta_name      College Point
nta                    QN23
latitude          40.776345
longitude        -73.841645
Name: 15678, dtype: object
Unnamed: 0               541901
tree_id                   35735
tree_dbh                     29
health                     Good
steward                     NaN
postcode                  11367
borough                  Queens
cncldist                     24
nta_name      Kew Gardens Hills
nta                        QN37
latitude              40.720378
longitude            -73.818658
Name: 41559, dtype: object
Unnamed: 0        400553
tree_id           600662
tree_dbh              32
health              Good
steward              NaN
postcode           11358
borough           Queens
cncldist              20
nta_name      Auburndale
nta                 QN48
latitude       40.751627
longitude     -73.784678
Name: 29115, dtype: object
Unnamed: 0                                            155561
tree_id                                               337956
tree_dbh                                                  21
health                                                  Good
steward                                                 1or2
postcode                                               11234
borough                                             Brooklyn
cncldist                                                  46
nta_name      Georgetown-Marine Park-Bergen Beach-Mill Basin
nta                                                     BK45
latitude                                           40.606154
longitude                                         -73.903137
Name: 11424, dtype: object
Unnamed: 0         657289
tree_id            167273
tree_dbh                3
health               Good
steward               NaN
postcode            11415
borough            Queens
cncldist               29
nta_name      Kew Gardens
nta                  QN60
latitude        40.709774
longitude      -73.827451
Name: 51189, dtype: object
Unnamed: 0                                                99673
tree_id                                                  298328
tree_dbh                                                     24
health                                                     Good
steward                                                     NaN
postcode                                                  10303
borough                                           Staten Island
cncldist                                                     49
nta_name      Mariner's Harbor-Arlington-Port Ivory-Granitev...
nta                                                        SI12
latitude                                              40.624152
longitude                                            -74.152602
Name: 7671, dtype: object
Unnamed: 0                                             269229
tree_id                                                484440
tree_dbh                                                   31
health                                                   Good
steward                                                   NaN
postcode                                                10473
borough                                                 Bronx
cncldist                                                   18
nta_name      Soundview-Castle Hill-Clason Point-Harding Park
nta                                                      BX09
latitude                                            40.820393
longitude                                          -73.869379
Name: 19235, dtype: object
Unnamed: 0           443144
tree_id              665614
tree_dbh                 15
health                 Good
steward                 NaN
postcode              11433
borough              Queens
cncldist                 27
nta_name      South Jamaica
nta                    QN01
latitude          40.696488
longitude        -73.777157
Name: 33171, dtype: object
Unnamed: 0             22411
tree_id               205290
tree_dbh                   9
health                  Good
steward                  NaN
postcode               11237
borough             Brooklyn
cncldist                  37
nta_name      Bushwick North

In [ ]:
fig = folium.Figure(width=800, height=320) #to set the size of the map on your own
m = folium.Map (location=(40.693, -73.9875), zoom_start=16)

#iterate over our dataset
#for each row, add a market at the location of that tree

for idx, item in df.sample(1000).iterrows(): 
    print(item)

    folium.Marker (location=(item['latitude'], item['longitude']),
              tooltip = str(item['tree_id']),
               popup=item['health'],
               icon=folium.Icon(icon="star", color="green")
               ).add_to(m) #add a marker for each point that you want to mark
    
fig.add_child(m)

In [22]:
df["nta_name"].value_counts()

nta_name
Bayside-Bayside Hills                   975
Douglas Manor-Douglaston-Little Neck    915
Upper West Side                         809
Kew Gardens Hills                       785
Park Slope-Gowanus                      777
                                       ...
Brighton Beach                           28
Starrett City                            17
West Brighton                            12
Battery Park City-Lower Manhattan        10
Stuyvesant Town-Cooper Village            6
Name: count, Length: 188, dtype: int64

In [23]:
downtown_df = df[df['nta_name'] == 'DUMBO-Vinegar Hill-Downtown Brooklyn-Boreum Hill']

Empty DataFrame
Columns: [Unnamed: 0, tree_id, tree_dbh, health, steward, postcode, borough, cncldist, nta_name, nta, latitude, longitude]
Index: []

In [26]:
#code to limit analysis to downtown brooklyn
fig = folium.Figure(width=800, height=320) #to set the size of the map on your own
m = folium.Map (location=(40.693, -73.9875), zoom_start=16)

#iterate over our dataset
#for each row, add a market at the location of that tree

for idx, item in downtown_df.iterrows(): 
    print(item)

    folium.Marker (location=(item['latitude'], item['longitude']),
              tooltip = str(item['tree_id']),
               popup=item['health'],
               icon=folium.Icon(icon="star", color="green")
               ).add_to(m) #add a marker for each point that you want to mark
    
fig.add_child(m)

NameError: name 'downtown_df' is not defined

In [ ]:
fig = folium.Figure(width=800, height=320) #to set the size of the map on your own
m = folium.Map (location=(40.7128, -74.0061), zoom_start=14, prefer_canvas=True)

#iterate over our dataset
#for each row, add a market at the location of that tree

for idx, item in df.sample(1000).iterrows(): 
    print(item)

    folium.Circle (location=(item['latitude'], item['longitude']),
              radius = 6,
               fill = True,
               opacity =0.5,
               color = 'blue'
               ).add_to(m) 
    
fig.add_child(m)

Unnamed: 0          159017
tree_id             343746
tree_dbh                24
health                Good
steward                NaN
postcode             11375
borough             Queens
cncldist                29
nta_name      Forest Hills
nta                   QN17
latitude         40.732063
longitude       -73.843878
Name: 11785, dtype: object
Unnamed: 0        407586
tree_id           599986
tree_dbh              25
health              Good
steward              NaN
postcode           11357
borough           Queens
cncldist              19
nta_name      Whitestone
nta                 QN49
latitude        40.79227
longitude     -73.820672
Name: 29608, dtype: object
Unnamed: 0                  242201
tree_id                     420578
tree_dbh                        20
health                        Good
steward                        NaN
postcode                     11365
borough                     Queens
cncldist                        24
nta_name      Fresh Meadows-Utopia
nta                           QN41
latitude                 40.737285
longitude               -73.794097
Name: 17068, dtype: object
Unnamed: 0       424954
tree_id          646657
tree_dbh             29
health             Good
steward             NaN
postcode          11421
borough          Queens
cncldist             32
nta_name      Woodhaven
nta                QN53
latitude      40.696855
longitude    -73.849595
Name: 31369, dtype: object
Unnamed: 0                                520934
tree_id                                    15368
tree_dbh                                       9
health                                      Good
steward                                      NaN
postcode                                   11365
borough                                   Queens
cncldist                                      24
nta_name      Pomonok-Flushing Heights-Hillcrest
nta                                         QN38
latitude                               40.737435
longitude                             -73.807533
Name: 39006, dtype: object
Unnamed: 0        85801
tree_id          257750
tree_dbh              3
health             Good
steward             NaN
postcode          11209
borough        Brooklyn
cncldist             43
nta_name      Bay Ridge
nta                BK31
latitude      40.621961
longitude     -74.02378
Name: 6566, dtype: object
Unnamed: 0                                544086
tree_id                                    50128
tree_dbh                                      28
health                                      Good
steward                                      NaN
postcode                                   11365
borough                                   Queens
cncldist                                      24
nta_name      Pomonok-Flushing Heights-Hillcrest
nta                                         QN38
latitude                               40.734714
longitude                             -73.806531
Name: 41692, dtype: object
Unnamed: 0           195673
tree_id              397569
tree_dbh                  2
health                 Good
steward                 NaN
postcode              10312
borough       Staten Island
cncldist                 51
nta_name      Arden Heights
nta                    SI48
latitude          40.544879
longitude        -74.185337
Name: 14345, dtype: object
Unnamed: 0                     30399
tree_id                       232097
tree_dbh                          22
health                          Good
steward                          NaN
postcode                       10454
borough                        Bronx
cncldist                           8
nta_name      Mott Haven-Port Morris
nta                             BX39
latitude                   40.805523
longitude                 -73.924624
Name: 2226, dtype: object
Unnamed: 0       341457
tree_id          555576
tree_dbh              3
health             Fair
steward            1or2
postcode          11101
borough          Queens
cncldist             26
nta_name        Astoria
nta                QN70
latitude      40.754486
longitude    -73.922744
Name: 24229, dtype: object
Unnamed: 0        389247
tree_id           601242
tree_dbh              35
health              Good
steward              NaN
postcode           11358
borough           Queens
cncldist              19
nta_name      Auburndale
nta                 QN48
latitude       40.755299
longitude     -73.792548
Name: 28139, dtype: object
Unnamed: 0           345057
tree_id              535389
tree_dbh                 13
health                 Poor
steward                 NaN
postcode              10312
borough       Staten Island
cncldist                 51
nta_name        Great Kills
nta                    SI54
latitude          40.560673
longitude        -74.168198
Name: 24595, dtype: object
Unnamed: 0                                 31286
tree_id                                   221405
tree_dbh                                      22
health                                      Fair
steward                                      NaN
postcode                                   11432
borough                                   Queens
cncldist                                      24
nta_name      Pomonok-Flushing Heights-Hillcrest
nta                                         QN38
latitude                               40.719916
longitude                             -73.790577
Name: 2432, dtype: object
Unnamed: 0                                475319
tree_id                                   696399
tree_dbh                                      18
health                                      Good
steward                                      NaN
postcode                                   11367
borough                                   Queens
cncldist                                      24
nta_name      Pomonok-Flushing Heights-Hillcrest
nta                                         QN38
latitude                               40.732538
longitude                             -73.810896
Name: 36046, dtype: object
Unnamed: 0        488537
tree_id           709928
tree_dbh               7
health              Good
steward              NaN
postcode           11214
borough         Brooklyn
cncldist              43
nta_name      Bath Beach
nta                 BK27
latitude        40.60548
longitude     -74.010654
Name: 37120, dtype: object
Unnamed: 0           354702
tree_id              535855
tree_dbh                 29
health                 Good
steward                 NaN
postcode              10312
borough       Staten Island
cncldist                 51
nta_name        Great Kills
nta                    SI54
latitude          40.538259
longitude        -74.154655
Name: 25256, dtype: object
Unnamed: 0                                               336209
tree_id                                                  538603
tree_dbh                                                     14
health                                                     Good
steward                                                     NaN
postcode                                                  10306
borough                                           Staten Island
cncldist                                                     50
nta_name      Todt Hill-Emerson Hill-Heartland Village-Light...
nta                                                        SI24
latitude                                              40.578012
longitude                                            -74.118313
Name: 23854, dtype: object
Unnamed: 0                     466742
tree_id                        692481
tree_dbh                           32
health                           Good
steward                           NaN
postcode                        11432
borough                        Queens
cncldist                           24
nta_name      Briarwood-Jamaica Hills
nta                              QN35
latitude                     40.71576
longitude                  -73.798855
Name: 35125, dtype: object
Unnamed: 0                 360724
tree_id                    568483
tree_dbh                        3
health                       Good
steward                      1or2
postcode                    11233
borough                  Brooklyn
cncldist                       41
nta_name      Crown Heights North
nta                          BK61
latitude                40.671676
longitude               -73.92239
Name: 26075, dtype: object
Unnamed: 0                                            454188
tree_id                                               676664
tree_dbh                                                  29
health                                                  Good
steward                                                  NaN
postcode                                               11234
borough                                             Brooklyn
cncldist                                                  46
nta_name      Georgetown-Marine Park-Bergen Beach-Mill Basin
nta                                                     BK45
latitude                                           40.613746
longitude                                         -73.922354
Name: 34089, dtype: object
Unnamed: 0           156206
tree_id              353849
tree_dbh                 23
health                 Good
steward                 NaN
postcode              10314
borough       Staten Island
cncldist                 50
nta_name        Westerleigh
nta                    SI07
latitude          40.610001
longitude        -74.139258
Name: 11491, dtype: object
Unnamed: 0           460151
tree_id              649947
tree_dbh                 30
health                 Good
steward                 NaN
postcode              11355
borough              Queens
cncldist                 20
nta_name      East Flushing
nta                    QN52
latitude          40.750596
longitude        -73.815673
Name: 34505, dtype: object
Unnamed: 0                276092
tree_id                   496100
tree_dbh                       5
health                      Good
steward                     1or2
postcode                   10472
borough                    Bronx
cncldist                      18
nta_name      Soundview-Bruckner
nta                         BX55
latitude               40.827254
longitude             -73.878792
Name: 19606, dtype: object
Unnamed: 0       313985
tree_id          525290
tree_dbh             12
health             Good
steward             NaN
postcode          11373
borough          Queens
cncldist             25
nta_name       Elmhurst
nta                QN29
latitude      40.739927
longitude    -73.871866
Name: 22640, dtype: object
Unnamed: 0                                       23905
tree_id                                         216222
tree_dbh                                            12
health                                            Good
steward                                            NaN
postcode                                         10465
borough                                          Bronx
cncldist                                            13
nta_name      Schuylerville-Throgs Neck-Edgewater Park
nta                                               BX52
latitude                                     40.813134
longitude                                   -73.825229
Name: 1959, dtype: object
Unnamed: 0       612172
tree_id          116747
tree_dbh             18
health             Good
steward             NaN
postcode          11223
borough        Brooklyn
cncldist             44
nta_name      Homecrest
nta                BK25
latitude      40.606053
longitude    -73.966022
Name: 47502, dtype: object
Unnamed: 0                                        316677
tree_id                                           520915
tree_dbh                                              15
health                                              Good
steward                                              NaN
postcode                                           10312
borough                                    Staten Island
cncldist                                              51
nta_name      Annadale-Huguenot-Prince's Bay-Eltingville
nta                                                 SI01
latitude                                        40.52588
longitude                                      -74.16669
Name: 22701, dtype: object
Unnamed: 0                                      657339
tree_id                                         153102
tree_dbh                                            11
health                                            Good
steward                                            NaN
postcode                                         11201
borough                                       Brooklyn
cncldist                                            39
nta_name      Carroll Gardens-Columbia Street-Red Hook
nta                                               BK33
latitude                                     40.687916
longitude                                   -73.994039
Name: 51196, dtype: object
Unnamed: 0       493170
tree_id          718874
tree_dbh              3
health             Good
steward             NaN
postcode          11435
borough          Queens
cncldist             28
nta_name        Jamaica
nta                QN61
latitude      40.693611
longitude    -73.810178
Name: 37408, dtype: object
Unnamed: 0          367258
tree_id             581325
tree_dbh                23
health                Good
steward                NaN
postcode             11434
borough             Queens
cncldist                27
nta_name      Baisley Park
nta                   QN76
latitude         40.686917
longitude       -73.782432
Name: 26659, dtype: object
Unnamed: 0                               587482
tree_id                                   86277
tree_dbh                                      4
health                                     Good
steward                                     NaN
postcode                                  10030
borough                               Manhattan
cncldist                                      9
nta_name      Central Harlem North-Polo Grounds
nta                                        MN03
latitude                              40.817819
longitude                            -73.947295
Name: 45392, dtype: object
Unnamed: 0                  639370
tree_id                     133036
tree_dbh                        14
health                        Fair
steward                        NaN
postcode                     11236
borough                   Brooklyn
cncldist                        45
nta_name      Rugby-Remsen Village
nta                           BK96
latitude                 40.649348
longitude               -73.920311
Name: 49654, dtype: object
Unnamed: 0                    350816
tree_id                       551552
tree_dbh                           4
health                          Good
steward                          NaN
postcode                       10454
borough                        Bronx
cncldist                           8
nta_name      Mott Haven-Port Morris
nta                             BX39
latitude                    40.80684
longitude                 -73.915313
Name: 24976, dtype: object
Unnamed: 0       601024
tree_id          109566
tree_dbh             11
health             Good
steward             NaN
postcode          11385
borough          Queens
cncldist             34
nta_name      Ridgewood
nta                QN20
latitude      40.705103
longitude    -73.913583
Name: 46608, dtype: object
Unnamed: 0                  201506
tree_id                     406365
tree_dbh                        31
health                        Fair
steward                        NaN
postcode                     11365
borough                     Queens
cncldist                        24
nta_name      Fresh Meadows-Utopia
nta                           QN41
latitude                 40.735827
longitude               -73.789715
Name: 14721, dtype: object
Unnamed: 0                      439534
tree_id                         654106
tree_dbh                             2
health                            Fair
steward                           1or2
postcode                         11693
borough                         Queens
cncldist                            32
nta_name      Hammels-Arverne-Edgemere
nta                               QN12
latitude                     40.587509
longitude                     -73.8173
Name: 32889, dtype: object
Unnamed: 0                                            114866
tree_id                                               300903
tree_dbh                                                  30
health                                                  Good
steward                                                  NaN
postcode                                               11235
borough                                             Brooklyn
cncldist                                                  48
nta_name      Sheepshead Bay-Gerritsen Beach-Manhattan Beach
nta                                                     BK17
latitude                                           40.592989
longitude                                         -73.938448
Name: 8668, dtype: object
Unnamed: 0                  336661
tree_id                     559717
tree_dbh                         4
health                        Good
steward                        NaN
postcode                     11212
borough                   Brooklyn
cncldist                        41
nta_name      Rugby-Remsen Village
nta                           BK96
latitude                 40.664607
longitude               -73.928039
Name: 23994, dtype: object
Unnamed: 0          220623
tree_id             437819
tree_dbh                15
health                Good
steward                NaN
postcode             10460
borough              Bronx
cncldist                17
nta_name      East Tremont
nta                   BX17
latitude         40.846168
longitude       -73.882715
Name: 15964, dtype: object
Unnamed: 0       286822
tree_id          411426
tree_dbh             29
health             Good
steward             NaN
postcode          11102
borough          Queens
cncldist             22
nta_name        Astoria
nta                QN70
latitude      40.768147
longitude    -73.919075
Name: 20477, dtype: object
Unnamed: 0       133426
tree_id          315738
tree_dbh             11
health             Fair
steward            1or2
postcode          11378
borough          Queens
cncldist             30
nta_name        Maspeth
nta                QN30
latitude      40.725026
longitude     -73.90444
Name: 9831, dtype: object
Unnamed: 0                                 421603
tree_id                                    591383
tree_dbh                                       18
health                                       Good
steward                                       NaN
postcode                                    11001
borough                                    Queens
cncldist                                       23
nta_name      Glen Oaks-Floral Park-New Hyde Park
nta                                          QN44
latitude                                40.733954
longitude                              -73.704004
Name: 30930, dtype: object
Unnamed: 0                                     66180
tree_id                                       277188
tree_dbh                                          24
health                                          Good
steward                                          NaN
postcode                                       10012
borough                                    Manhattan
cncldist                                           3
nta_name      SoHo-TriBeCa-Civic Center-Little Italy
nta                                             MN24
latitude                                   40.725464
longitude                                 -74.002234
Name: 5155, dtype: object

Choropleth

In [ ]:
import json
geo_json_data = json.load(open())


#zoned out